language: node_js

node_js: 
  - "7"
  - "8"
  - "9"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm test
  - npm build

notifications:
  email:
    on_success: change
    on_failure: always